### ISSUE TITLE
zyboz7 r23.1.0 compile error

### ISSUE THREAD

**Issue by chenguoping76** [mathworks/buildroot#8]
./../misc/create_inode.c: At top level:
./../misc/create_inode.c:395:18: error: conflicting types for ‘copy_file_range’
 static errcode_t copy_file_range(ext2_filsys fs, int fd, ext2_file_t e2_file,
                  ^~~~~~~~~~~~~~~
In file included from ./../misc/create_inode.c:19:0:
/usr/include/unistd.h:1110:9: note: previous declaration of ‘copy_file_range’ was here
 ssize_t copy_file_range (int __infd, __off64_t *__pinoff,
         ^~~~~~~~~~~~~~~
Makefile:423: recipe for target 'create_inode.o' failed
make[4]: *** [create_inode.o] Error 1
make[4]: *** Waiting for unfinished jobs....
Makefile:405: recipe for target 'all-progs-recursive' failed
make[3]: *** [all-progs-recursive] Error 1
Makefile:340: recipe for target 'all' failed
make[2]: *** [all] Error 2
package/pkg-generic.mk:227: recipe for target '/home/cgp/workspace/mathworks_buildroot/buildroot/output/zybo_linux_linaro/build/host-e2fsprogs-1.43.4/.stamp_built' failed
make[1]: *** [/home/cgp/workspace/mathworks_buildroot/buildroot/output/zybo_linux_linaro/build/host-e2fsprogs-1.43.4/.stamp_built] Error 2
Makefile:16: recipe for target '_all' failed
make: *** [_all] Error 2
Uncaught exception
Traceback (most recent call last):
  File "./build.py", line 191, in <module>
    build_target(args, catalog)
  File "./build.py", line 89, in build_target
    subproc(argStr, cwd=args['outputDir'])
  File "/home/cgp/workspace/mathworks_buildroot/buildroot/board/mathworks/common/scripts/helper_func.py", line 492, in subproc
    _SUBPROC_LOGGER.call(args, cwd=cwd, shell=shell)
  File "/home/cgp/workspace/mathworks_buildroot/buildroot/board/mathworks/common/scripts/helper_func.py", line 77, in call
    raise subprocess.CalledProcessError(self.proc.returncode, self.strArgs(args), None)
CalledProcessError: Command 'make legal-info all' returned non-zero exit status 2

**Comment by Abraxas3d** [comment]
./build.py -b zc706 -p zynq

```
Cannot execute cross-compiler '/opt/linaro/aarch32-6.3.1-2017.02/bin/arm-linux-gnueabihf-gcc'
package/pkg-generic.mk:217: recipe for target '/home/abraxas3d/haifuraiya/buildroot/output/zc706_linux_linaro/build/toolchain-external-custom/.stamp_configured' failed
make[1]: *** [/home/abraxas3d/haifuraiya/buildroot/output/zc706_linux_linaro/build/toolchain-external-custom/.stamp_configured] Error 1
Makefile:16: recipe for target '_all' failed
make: *** [_all] Error 2
Uncaught exception
Traceback (most recent call last):
  File "./build.py", line 191, in <module>
    build_target(args, catalog)
  File "./build.py", line 89, in build_target
    subproc(argStr, cwd=args['outputDir'])
  File "/home/abraxas3d/haifuraiya/buildroot/board/mathworks/common/scripts/helper_func.py", line 492, in subproc
    _SUBPROC_LOGGER.call(args, cwd=cwd, shell=shell)
  File "/home/abraxas3d/haifuraiya/buildroot/board/mathworks/common/scripts/helper_func.py", line 77, in call
    raise subprocess.CalledProcessError(self.proc.returncode, self.strArgs(args), None)
CalledProcessError: Command 'make legal-info all' returned non-zero exit status 2

```

Similar error to above. 

I guess the problem is with .stamp_configured? 

I'm on Ubuntu trying to build the SD card image for a zc706 so we can get started using an analog devices radio card with MATLAB.
